% Generate the Mesh
%
% If the mesh generated by this code does not meet your requirements,
% you can replace it with a custom-generated mesh and the corresponding mask inside the mesh.
% If some regions of the mesh are too dense, 
% you can manually adjust the Mask to improve the mesh quality.

isiso = true; %if the data has isotropic voxel size
if isiso
    radbound=3;
else 
    radbound=4;
end
%Mask(:,:,2)=0;
[mesh, mask] = generateMeshAndMask(radbound, Mask, voxel_size, isiso);
mask = double(mask);
plotModel(mesh);